FROM apache/airflow:2.9.1
USER root
RUN apt-get update && apt-get install -y gcc g++ && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir \
    Pillow \
    numpy \
    pandas \
    scikit-learn \
    tqdm \
    torch \
    torchvision \
    albumentations \
    PyYAML \
    opencv-python-headless \
    mlflow \
    evidently \
    requests
