FROM node:20-alpine AS builder
WORKDIR /app
ARG REACT_APP_API_URL
ARG REACT_APP_API_PREFIX
ARG REACT_APP_GRAFANA_URL
ARG REACT_APP_MLFLOW_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_API_PREFIX=$REACT_APP_API_PREFIX
ENV REACT_APP_GRAFANA_URL=$REACT_APP_GRAFANA_URL
ENV REACT_APP_MLFLOW_URL=$REACT_APP_MLFLOW_URL
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
